// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240516080252_AddDeliferyInfoAndSeedData")]
    partial class AddDeliferyInfoAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.DeliveryInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("DeliveryInProgress")
                        .HasColumnType("bit");

                    b.Property<bool>("PickUpInProgress")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.ToTable("DeliveryInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f03eba25-3860-46f6-a661-5d2c8d04db83"),
                            CourierId = new Guid("c684178f-a323-4947-a7ff-3c725f349fa3"),
                            Date = new DateOnly(2024, 5, 20),
                            DeliveryInProgress = true,
                            PickUpInProgress = false
                        },
                        new
                        {
                            Id = new Guid("2a07b9b0-5a33-46f5-a2b7-2f5eb2744333"),
                            CourierId = new Guid("c684178f-a323-4947-a7ff-3c725f349fa3"),
                            Date = new DateOnly(2024, 5, 21),
                            DeliveryInProgress = false,
                            PickUpInProgress = true
                        });
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c684178f-a323-4947-a7ff-3c725f349fa3"),
                            Email = "courier@gmail.com",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
                        });
                });

            modelBuilder.Entity("Domain.Models.DeliveryInfo", b =>
                {
                    b.HasOne("Domain.Models.User", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courier");
                });
#pragma warning restore 612, 618
        }
    }
}
